[package]
name = "tree_adoption"
version = "1.0.0"
authors = ["Tree Adoption Platform"]

[addresses]
tree_adoption = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "83641d3f083762f31700060e5e95fbb1cbc28bf0" }